## 1. Data Types

In [ ]:
#String
str = 'String'
print(str)
str = "String value"
print(str)
str = ''' how are things
things are fine
things are good'''
print(str)

String
String value
 how are things
things are fine
things are good


In [ ]:
#Numbers
a = 5
print(a, "is of type", type(a))
b=1.5
print(b, "is of type", type(b))
c = 1+2j
print(c, "is of type", type(c))
print(a+b)
print(a+c)

5 is of type <class 'int'>
1.5 is of type <class 'float'>
(1+2j) is of type <class 'complex'>
6.5
(6+2j)


In [ ]:
#List of Strings
a = ["a", "b", "c"]
print(a)
#List of Ints
a = [1,2,3]
print(a)
#List Of String, Int and Float
a = ['a', 1, 2.3]
print(a)
#List of Lists
a = [[1,2], [3,4]]
print(a)

['a', 'b', 'c']
[1, 2, 3]
['a', 1, 2.3]
[[1, 2], [3, 4]]


In [ ]:
#Dictionary
{"Name": "Shaw"}
# a dictionary with multiple key-value pairs
{"Name":"Shaw", "Age":20, "Subjects":['Math', 'English']}
# a list of dictionaries
[{"Name":"Shen", "Age":25, "Subjects":['Math', 'English']},{"Name":"Shun", "Age":28, "Subjects":['Math', 'English']}]
# a nested dictionary
{"user":{"name":"Shub", "age":20,"subjects":['Math', 'English']}, 'last_login':"2024-09-09", "is_active":True}

# 2. Variables

In [ ]:
user_name = 'Shub'
user_interest = ['AI', 'Music', 'Talks']
print(f"{user_name} is interested in {user_interest}")

Shub is interested in ['AI', 'Music', 'Talks']


# 3. Loops and Conditions

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
user_interest = ['AI', 'Music', 'Talks']
for interest in user_interest:
    print(interest)

AI
Music
Talks


In [ ]:
user_dict= {"Name":"Shaw", "Age":20, "Subjects":['Math', 'English']}
for key in user_dict:
    print(key, user_dict[key])

Name Shaw
Age 20
Subjects ['Math', 'English']


In [ ]:
if user_dict['Age'] > 5:
    print(user_dict['Age'])

20


In [ ]:
user_dict= [{"Name":"shen", "Age":20, "Subjects":['AI', 'English']},{"Name":"shub", "Age":20, "Subjects":['Math', 'English']}]

count = 0

for user in user_dict:
    if 'English' in user['Subjects']:
        count += 1
print(count)

2


# 4. Functions

In [ ]:
#In built Functions : Print
user_dict= {"Name":"Shaw", "Age":20, "Subjects":['Math', 'English']}

for key in user_dict:
    print(key, user_dict[key])
    print(key, type(user_dict.get(key)))

Name Shaw
Name <class 'str'>
Age 20
Age <class 'int'>
Subjects ['Math', 'English']
Subjects <class 'list'>


In [ ]:
# In-built Functions : String function upper and lower

# ## Data Types
# String
str = 'String'
print(str.upper())  # Convert to uppercase
print(str.lower())  # Convert to lowercase

str = "String value"
print(str.upper())  # Convert to uppercase
print(str.lower())  # Convert to lowercase

STRING
string
STRING VALUE
string value


# 5. Libraries : Numpy and Pandas

# Numpy

In [ ]:
#1 : Import
import numpy as np

In [ ]:
#2. create vectors
v = np.array([1, 2, 3])
z = np.array([4, 5, 6])

In [ ]:
#3. create a matrix from vectors
X = np.array([v, 2*v, v/2])
print(X)

[[1.  2.  3. ]
 [2.  4.  6. ]
 [0.5 1.  1.5]]


In [ ]:
#4. Addition and subtraction of vectors
print(v+z)
print(v-z)

#5. matrix multiplication
print(X.shape)
print(v.shape)
print(np.matmul(X, v))

[5 7 9]
[-3 -3 -3]
(3, 3)
(3,)
[14. 28.  7.]


In [ ]:
#6. Cross and Dot Products
print(np.dot(v, z))
print(np.cross(v, z))

32
[-3  6 -3]


In [ ]:
#7. Reshape and Flatten
print(X.reshape(9,))
print(X.flatten())

[1.  2.  3.  2.  4.  6.  0.5 1.  1.5]
[1.  2.  3.  2.  4.  6.  0.5 1.  1.5]


# Pandas

In [ ]:
#import pandas
import pandas as pd

In [ ]:
# Creating a Series
ds = pd.Series(v)
print(ds)

0    1
1    2
2    3
dtype: int64


In [ ]:
#Creating a Dataframe
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
lst = ['ai', '430', 'makes', 'you', 'awesome']

# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)

         0
0       ai
1      430
2    makes
3      you
4  awesome


In [ ]:
# Calling DataFrame constructor on Matrix
print(X)
df = pd.DataFrame(X)
print(df)

[[1.  2.  3. ]
 [2.  4.  6. ]
 [0.5 1.  1.5]]
     0    1    2
0  1.0  2.0  3.0
1  2.0  4.0  6.0
2  0.5  1.0  1.5


In [ ]:
df.head(2)

0    1    2
0  1.0  2.0  3.0
1  2.0  4.0  6.0